spring.application.name=ga-client
spring.datasource.url=jdbc:postgresql://localhost:5432/gur_academy_local
spring.datasource.username=gur_academy
spring.datasource.password=gur_academy
spring.datasource.driver-class-name =org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = validate
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size = 10

spring.profiles.active=local

logging.level.org.springframework.web=DEBUG
